name: ml-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - xgboost
  - scikit-learn
  - matplotlib
  - seaborn
  - streamlit
  - requests
  - python-dotenv
  - ipykernel